@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package net.katsstuff.teamnightclipse.danmakucore.entity.living;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;